apiVersion: apps/v1
kind: Deployment
metadata:
 name: bird-app
 namespace: {{ .Values.namespace }}
 labels:
   app: bird-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: bird-app
 template:
   metadata:
     annotations:
       vault.hashicorp.com/agent-inject: "true"
       vault.hashicorp.com/role: internal-app
       vault.hashicorp.com/agent-inject-secret-config: "internal/database/config"
       vault.hashicorp.com/agent-inject-template-config: |
          {{`{{ with secret "internal/database/config" -}}
            export TEST_SECRET="{{ .Data.data.test_secret }}"
          {{- end }}`}}
     labels:
       app: bird-app
       date: "{{ now | unixEpoch }}" # used to force the recreation of pods and the pulling of images from ECR
   spec:
     serviceAccountName: internal-app
     containers:
       - name: bird-app
         image: geddunicorn/bird-app:latest
         imagePullPolicy: Always
         command: ['sh', '-c'] # overrides ENTRYPOINT in Dockerfile
         args: ['source /vault/secrets/config && /root/bird-app'] # overrides CMD in Dockerfile
         envFrom:
           - configMapRef:
               name: birdapp-config
         resources:
           requests:
             cpu: 100m
             memory: 512Mi
           limits:
             cpu: 250m
             memory: 1024Mi
         ports:
           - name: http
             containerPort: 8080
             protocol: TCP
{{/*     initContainers:*/}}
{{/*       - name: init-db*/}}
{{/*         image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3*/}}
{{/*         command: ['sh', '-c', 'until nslookup pg-service.default; do echo waiting for pg-service; sleep 2; done;']*/}}
