apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bird-app
spec:
  interval: 1m
  chart:
    spec:
      chart: chart
      version: ">=1.0.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m